In [3]:
import sys, os
sys.path.insert(0,'/Users/mbbssnw3/Dropbox (The University of Manchester)/ACTIVE/COURSE--OptContFinance/code/stochastic_control')

In [4]:
import numpy as np
from stochastic_control.discrete_control import LQR
from time import time
from IPython.display import clear_output

ModuleNotFoundError: No module named 'stochastic_control.discrete_control'

In [1]:
def riccati(L,A,B,C):
    ''' riccati equation solver
    
    # Summary
        One iteration of the riccati recursion for linear dynamic
            x' = A x + B a
        and cost
            (x,a) C (x,a)
        given value function at the next time is given by the matrix L
    
    # Arguments
        L,C -- np.matrix (should be semi-definite)
        A,B -- np.matrix
    '''

    dim_x, dim_a = B.shape
    
    R = C[0:dim_x][C[0:dim_x]]
    U = C[0:dim_x][C[dim_x:]]
    Q = C[dim_x:][C[dim_x:]]
    
    A_T = A.transpose()
    B_T = B.transpose()
    U_T = U.transpose()
    
    L_new = R + A_T*L*A - (A_T*L*B+U) * (np.linalg.inv( Q+B_T*L*B )) * (B_T*L*A+U)
    
    return L_new
    

SyntaxError: invalid syntax (<ipython-input-1-8f0b008672cd>, line 16)

In [5]:
A = np.matrix([[1,2],[3,4],[5,6]])

In [19]:
A*A.transpose()

matrix([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [14]:
A[:][0:2]

matrix([[1, 2],
        [3, 4]])

In [15]:
A[:][2:]

matrix([[5, 6]])

In [17]:
A.transpose()

matrix([[1, 3, 5],
        [2, 4, 6]])