In [1]:
import sys, os
sys.path.insert(0,'/Users/mbbssnw3/Dropbox (The University of Manchester)/ACTIVE/COURSE--OptContFinance/code/stochastic_control')

In [2]:
import numpy as np
from stochastic_control.discrete_control import LQR
from time import time
from IPython.display import clear_output

ModuleNotFoundError: No module named 'stochastic_control.discrete_control'

In [ ]:
def riccati(L,A,B,C):
    ''' riccati recusion solver:
    
        L_new = R + A'LA + (A'LB+U)[Q+B'LB]^{-1} (B'LA+U')
    
    # Summary
        One iteration of the riccati recursion for linear dynamic
            x' = A x + B a
        and cost
            (x,a) C (x,a)
            
            C = [ R  U
                  U' Q ]
        given value function at the next time is given by the matrix L
    
    # Arguments
        L,C -- np.matrix (should be semi-definite)
        A,B -- np.matrix
    '''

    dim_x, dim_a = B.shape
    
    R = C[0:dim_x,0:dim_x]
    U = C[0:dim_x,dim_x:]
    Q = C[dim_x:,dim_x:]
    
    A_T = A.transpose()
    B_T = B.transpose()
    U_T = U.transpose()
    
    L_new = R + A_T*L*A - (A_T*L*B+U) * (np.linalg.inv( Q+B_T*L*B )) * (B_T*L*A+U_T)
    
    return L_new
    

## Speed control

## Rocket Ship

## Quadratic Trading

In [27]:
L = np.matrix([[1,0],[0,1]])
A = np.matrix([[1,0],[0,1]])
B = np.matrix([[1,0],[0,1]])
C = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [28]:
riccati(L,A,B,C)

matrix([[1.5, 0. ],
        [0. , 1.5]])

In [11]:
dim_x, dim_a = B.shape

In [24]:
R = C[0:dim_x,0:dim_x]

In [25]:
R

matrix([[1, 0],
        [0, 1]])

In [17]:
A.transpose()

matrix([[1, 3, 5],
        [2, 4, 6]])